name: dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  kt_dart: ^1.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dartz: ^0.10.1
  equatable: ^2.0.5


#  # UI
#  shimmer: ^1.1.2
#  cached_network_image: ^2.4.1
#  url_launcher: ^5.7.10
#  flutter_launcher_icons: ^0.8.0
#  package_info: ^0.4.3+2
#  youtube_player_flutter: ^7.0.0+7
#  flutter_svg: 0.19.0
#  liquid_pull_to_refresh: ^2.0.0
#  carousel_slider: ^2.3.1
#  lottie: ^0.7.0+1
#  fluttertoast: ^7.1.5
#
#  # Core
#  flutter_bloc: ^6.1.1
#  shared_preferences: ^0.5.12+4
#  equatable: ^1.2.5
#  get_it: ^5.0.3
#  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
